# -*- coding: utf-8 -*-
"""FlaskBackEnd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y5JydjEyl6pBAiAEQHDzOgDwZQAMs-pj
"""

from flask import *
from predict import predictImage #From predict.py import function named predict

app = Flask(__name__)

@app.route('/success', methods=['POST'])
def success():
  if request.method == 'POST':
     f=request.files['file']
  return predict(f)

if __name__== '__main__':
  app.run(host = '0.0.0.0 or whatever',debug = True)
